
site_name: Jo Simons
site_description: Documentation for Phc2Mqtt
site_url: https://sim0njo.github.io/phc2mqtt/
docs_dir: docs

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/home.gif
  
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.tracking

  font:
    text: Barlow
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tilde
  - meta
  - def_list
  - attr_list

nav:
  - Phc2Mqtt:
    - User Manual: Phc2Mqtt.md
    - Phc Modules: PhcModules.md
    - Simple Rule Server: SimpleRuleServer.md
#   - PCB Production Info: P2mGerbers.md
#   - Upgrading.md
#  - Windows&Linux Projects:
#    - MQTT Client: Upgrading.md
#    - MQTT Server: Upgrading.md
  - Downloads: Downloads.md
#    - Windows: Firmware-Builds.md
#    - Linux: Firmware-Builds.md
  - ESP Web Installer: "http://sim0njo.github.io/install"    